### ISSUE TITLE
전체 및 접속중인 회원 목록

### ISSUE THREAD

**Issue by junotb** [chatforyou-io/front-chatforyou-io#9]

**Comment by SeJonJ** [comment]
@SeJonJ 

유저 목록 조회 api 사용지 500 에러 발생
```json
{
    "code": "500",
    "message": "Unknown Server Error"
}
```

에러 서버 로그
```json
2024-11-23T17:39:45.507+09:00 ERROR 28969 --- [chatforyou.io] [nio-8443-exec-2] c.c.io.controller.ExceptionController    : RuntimeException: userIndex: no such index. channel: [id: 0x0883dfa8, L:/192.168.158.234:62195 - R:210.220.67.85/210.220.67.85:30678] command: (FT.SEARCH), promise: RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@6e48d5cb(incomplete)], params: [userIndex, *, RETURN, 1, user, SORTBY, userId, DESC, LIMIT, 0, ...]

org.redisson.client.RedisException: userIndex: no such index. channel: [id: 0x0883dfa8, L:/192.168.158.234:62195 - R:210.220.67.85/210.220.67.85:30678] command: (FT.SEARCH), promise: RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@6e48d5cb(incomplete)], params: [userIndex, *, RETURN, 1, user, SORTBY, userId, DESC, LIMIT, 0, ...]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:370) ~[redisson-3.16.6.jar:3.16.6]
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:198) ~[redisson-3.16.6.jar:3.16.6]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:137) ~[redisson-3.16.6.jar:3.16.6]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:113) ~[redisson-3.16.6.jar:3.16.6]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:530) ~[netty-codec-4.1.110.Final.jar:4.1.110.Final]
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) ~[netty-codec-4.1.110.Final.jar:4.1.110.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[netty-codec-4.1.110.Final.jar:4.1.110.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1407) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:918) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994) ~[netty-common-4.1.110.Final.jar:4.1.110.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.110.Final.jar:4.1.110.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.110.Final.jar:4.1.110.Final]
	at java.base/java.lang.Thread.run(Thread.java:842) ~[na:na]
```

**Comment by SeJonJ** [comment]
@junotb 
전체 및 접속중인 회원목록 조회 가능하도록 개발

로그인 된 사용자를 조회 가능하도록 redis 에 index 추가 :: userIndex
keyword, pageNum, pageSize 를 통해서 검색 옵션 설정 가능하도록 개발(채팅방과 동일)
keyword 로 해당 문자열을 포함하는 user id 및 user nickName 을 검색(like 검색)



관련 머지 리퀘스트 
https://github.com/chatforyou-io/ChatForYou.io-back/pull/15



# **API 명세서: 사용자 목록 조회**

## **1. 요청 (Request)**

### **HTTP 메서드**
`GET`

### **엔드포인트**
```
/user/list
```

### **호스트**
```
https://hjproject.kro.kr/chatforyou
```

### **헤더**
| 헤더          | 값                       | 설명                        |
|---------------|--------------------------|-----------------------------|
| `Content-Type` | `application/json`       | 요청 본문의 형식             |
| `Authorization` | `Bearer <토큰>`          | 인증 토큰                   |

### **쿼리 파라미터**
| 파라미터      | 타입     | 필수 여부 | 설명                                      |
|---------------|---------|-----------|-------------------------------------------|
| `keyword`    | `string`| 선택      | 사용자 이름 또는 키워드 검색               |
| `pageSize`   | `int`   | 선택      | 한 페이지에 표시할 사용자 수 (기본값: 10)   |
| `pageNum`    | `int`   | 선택      | 조회할 페이지 번호 (기본값: 1)             |


## **1. 응답 (Response)**

### **상태 코드**
| 코드 | 설명                          |
|------|-------------------------------|
| `200 OK` | 성공적으로 사용자 목록을 반환 |
| `400 Bad Request` | 잘못된 요청 형식           |
| `401 Unauthorized` | 인증 실패                  |
| `500 Internal Server Error` | 서버 오류              |

### **응답 예시**
```json
{
    "result": "success",
    "count": 1,
    "userList": [
        {
            "idx": 32,
            "id": "sejon@test.com",
            "name": "sejon",
            "nickName": "nicknameCC",
            "provider": ""
        }
    ]
}
```

### **응답 필드 설명**

| 필드             | 타입      | 설명                                      |
|------------------|-----------|-------------------------------------------|
| `result`         | `string`  | 요청 결과 상태 (`success` 또는 `error`)      |
| `count`          | `int`     | 반환된 사용자 수                          |
| `userList`       | `array`   | 사용자 목록 데이터                        |
| `userList.idx`   | `int`     | 사용자 인덱스                             |
| `userList.id`    | `string`  | 사용자 이메일                             |
| `userList.name`  | `string`  | 사용자 이름                               |
| `userList.nickName` | `string` | 사용자 닉네임                            |
| `userList.provider` | `string` | 소셜 로그인 제공자 (예: Google, Kakao)   |



## **3. 주의사항**

1. **Authorization** 헤더에 유효한 토큰이 반드시 필요합니다.
2. **쿼리 파라미터**는 URL에 포함되어야 합니다.
3. 페이지네이션과 검색 기능을 제공하므로, `pageSize`, `pageNum`, `keyword` 파라미터를 적절히 조정하여 사용하세요.

**Comment by SeJonJ** [comment]
@SeJonJ 
- 전체(접속 여부 상관 X) 조회 API
- 현재 있는 api 는 이름 검토 :: user/list -> user/list/current ???
++ 가능하다면
- 친구목록 조회 api path 검토 + 기능 확인

**Comment by SeJonJ** [comment]
@junotb 
https://github.com/chatforyou-io/ChatForYou.io-back/issues/21 로 수정 및 배포 완료 했습니다.
- 응답결과에 일부 수정사항이 있습니다 : totalCount, pageNum, pageSize 추가

```json
{
    "result": "success",
    "totalCount": 1,
    "pageNum": 0,
    "pageSize": 20,
    "userList": [
        {
            "idx": 25,
            "id": "test@mail.com",
            "name": "testuser",
            "nickName": "nicknameCC",
            "provider": ""
        }
    ]
}
```
